version: '3.8'

services:
  app:
    build: .
    image: turbo-charged-athletics:latest
    ports:
      - "8000:9000"
    volumes:
      - ./:/var/www/html
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: turbo_charged_athletics
      DB_USERNAME: root
      DB_PASSWORD: ""
    depends_on:
      - mysql

  depends_on:
      mysql:
        condition: service_healthy
  mysql:
    container_name: turbo-charged-athletics-mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: turbo_charged_athletics
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
